server:
  port: 8080
  servlet:
      context-path: /pokedex

resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 8
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 4
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 2s
        instances:
            kantoService:
                baseConfig: default
                failureRateThreshold: 50 
                
config:
    password: my-password               