server:
  port: 8080
  servlet:
      context-path: /pokedex

resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 2s
        instances:
            errorCallsMonitor:
                baseConfig: default
                failureRateThreshold: 50 