version: '3'
services:
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"
